### PR TITLE
Tl celebrity2

### PR DESCRIPTION
**Pull request by Tlane77**
Look and See what you think

### CODE REVIEW

**Review by bdanielle092 — APPROVED** [review]
fix merge problem

**Review by abernethyb — CHANGES_REQUESTED** [review]
This merge conflict looks like what we already de-conflicted.  Everything else in index looks good.  Let's see if this works.  but first, Images need to be moved to image folder.

**Review by abernethyb — APPROVED** [review]
Let's give this a go and see what happens.

**Review by bdanielle092 — APPROVED** [review]
good job

**Pull request merged**
